# Generated by Django 3.2.9 on 2021-11-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0002_sponsor_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_ko',
            field=models.CharField(default='', max_length=100),
        ),
    ]
