# Generated by Django 3.2.9 on 2021-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0004_auto_20211111_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('speaker_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(upload_to='images/speaker/')),
                ('bio', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
    ]
