# Generated by Django 3.2.9 on 2021-11-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0005_techsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(default=None, upload_to='images/speaker/')),
                ('bio', models.CharField(default='', max_length=1000)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('blog', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='email',
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='speaker_name',
        ),
        migrations.AddField(
            model_name='techsession',
            name='session_type',
            field=models.CharField(choices=[('Keynote', 'Keynote'), ('Sponsor', 'Sponsor'), ('Tech', 'Tech')], default='Tech', max_length=20),
        ),
        migrations.AddField(
            model_name='techsession',
            name='slide_url',
            field=models.FileField(default='', upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='techsession',
            name='video_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='techsession',
            name='speaker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openinfradays.speaker'),
        ),
    ]
