# Generated by Django 3.2.9 on 2021-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0006_auto_20211112_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
