# Generated by Django 3.2.9 on 2021-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0007_auto_20211112_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsession',
            name='slide_url',
            field=models.FileField(default='', null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='video_url',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
