# Generated by Django 3.2.9 on 2021-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0008_auto_20211112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsession',
            name='slide_url',
            field=models.FileField(blank=True, default='', upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
