# Generated by Django 3.2.9 on 2021-11-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0009_auto_20211112_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='blog',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
