# Generated by Django 3.2.9 on 2021-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0010_auto_20211112_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsession',
            name='qna_date',
            field=models.DateField(blank=True, default='2021-12-07'),
        ),
        migrations.AddField(
            model_name='techsession',
            name='qna_enable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='techsession',
            name='qna_time',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
