# Generated by Django 3.2.9 on 2021-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0011_auto_20211112_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsession',
            name='qna_location',
            field=models.CharField(default='Gather Town', max_length=100),
        ),
    ]
