# Generated by Django 3.2.9 on 2021-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0013_auto_20211112_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
