# Generated by Django 3.2.9 on 2021-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0014_speaker_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, upload_to='images/speaker/'),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='open_date',
            field=models.DateField(default='2021-12-07'),
        ),
    ]
