# Generated by Django 3.2.9 on 2021-11-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0015_auto_20211113_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=10000)),
                ('video1', models.CharField(blank=True, default='', max_length=100)),
                ('video2', models.CharField(blank=True, default='', max_length=100)),
                ('video3', models.CharField(blank=True, default='', max_length=100)),
                ('image1', models.ImageField(blank=True, default=None, upload_to='images/virtualbooth/')),
                ('image2', models.ImageField(blank=True, default=None, upload_to='images/virtualbooth/')),
                ('image3', models.ImageField(blank=True, default=None, upload_to='images/virtualbooth/')),
                ('link1', models.CharField(blank=True, default='', max_length=100)),
                ('link2', models.CharField(blank=True, default='', max_length=100)),
                ('link3', models.CharField(blank=True, default='', max_length=100)),
                ('link4', models.CharField(blank=True, default='', max_length=100)),
                ('link5', models.CharField(blank=True, default='', max_length=100)),
                ('sponsor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openinfradays.sponsor')),
            ],
        ),
    ]
