# Generated by Django 3.2.9 on 2021-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0016_virtualbooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbooth',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
