# Generated by Django 3.2.9 on 2021-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0021_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree_with_private',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='agree_with_sponsor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
