# Generated by Django 3.2.9 on 2021-11-29 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openinfradays', '0023_auto_20211125_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=100)),
                ('expired', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 15, 22, 30, 939594))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
