# Generated by Django 3.2.9 on 2021-12-02 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openinfradays', '0025_auto_20211129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 2, 30, 32, 688835)),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('Sapphire', 'Sapphire'), ('Gold', 'Gold'), ('Media', 'Media')], default='Gold', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('access_at', models.DateTimeField(default=datetime.datetime(2021, 12, 3, 2, 30, 32, 688980))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
