# Generated by Django 3.2.9 on 2021-12-03 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0026_auto_20211203_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualbooth',
            name='image1_link',
            field=models.FileField(blank=True, default='', upload_to='files/virtualbooth/'),
        ),
        migrations.AddField(
            model_name='virtualbooth',
            name='image2_link',
            field=models.FileField(blank=True, default='', upload_to='files/virtualbooth/'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 15, 50, 4, 94805)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 15, 50, 4, 94652)),
        ),
        migrations.CreateModel(
            name='SponsorNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, default='2021-12-07')),
                ('details', models.TextField(max_length=1000)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openinfradays.sponsor')),
            ],
        ),
    ]
