# Generated by Django 3.2.9 on 2021-12-04 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0028_auto_20211204_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsornight',
            name='details',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 1, 20, 1, 14779)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 1, 20, 1, 14568)),
        ),
    ]
