# Generated by Django 3.2.9 on 2021-12-04 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0029_auto_20211204_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsornight',
            name='event_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 2, 28, 49, 949709)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 2, 28, 49, 949531)),
        ),
    ]
