# Generated by Django 3.2.9 on 2021-12-04 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0030_auto_20211204_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('moderator', models.CharField(default='', max_length=120)),
                ('bof_date', models.DateField(default='2021-12-07')),
                ('bof_time', models.CharField(default='', max_length=30)),
                ('content', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 16, 4, 20, 264806)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 16, 4, 20, 264630)),
        ),
    ]
