# Generated by Django 3.2.9 on 2021-12-06 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0033_auto_20211205_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 1, 31, 4, 855794)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 1, 31, 4, 855629)),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='session_type',
            field=models.CharField(choices=[('Keynote', 'Keynote'), ('Sponsor', 'Sponsor'), ('Tech', 'Tech'), ('Community', 'Community')], default='Tech', max_length=20),
        ),
    ]
