# Generated by Django 3.2.9 on 2021-12-06 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0036_auto_20211206_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='request_ip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='access_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 18, 57, 12, 544484)),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 57, 12, 544302)),
        ),
    ]
